# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/eth/eth.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth || ORIG_REF_NAME==eth} -quiet] -quiet

# IP: bd/eth/ip/eth_rmii_axis_0_0/eth_rmii_axis_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_rmii_axis_0_0 || ORIG_REF_NAME==eth_rmii_axis_0_0} -quiet] -quiet

# IP: bd/eth/ip/eth_proc_sys_reset_0_0/eth_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_proc_sys_reset_0_0 || ORIG_REF_NAME==eth_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/eth/ip/eth_clk_wiz_0_0/eth_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_clk_wiz_0_0 || ORIG_REF_NAME==eth_clk_wiz_0_0} -quiet] -quiet

# IP: bd/eth/ip/eth_axis_gpio_0_0/eth_axis_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_axis_gpio_0_0 || ORIG_REF_NAME==eth_axis_gpio_0_0} -quiet] -quiet

# IP: bd/eth/ip/eth_tempSens_0_1/eth_tempSens_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_tempSens_0_1 || ORIG_REF_NAME==eth_tempSens_0_1} -quiet] -quiet

# XDC: c:/Users/rfebb/Desktop/Projects/ethernetTest5/ethernetTest5.gen/sources_1/bd/eth/eth_ooc.xdc
