# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rfebb/Desktop/nexEthernet/ip_repo/rmii_axis_1_0/src/data_fifo/data_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] -quiet

# XDC: c:/users/rfebb/desktop/projects/ethernettest5/ethernettest5.tmp/rmii_axis_v1_0_project/rmii_axis_v1_0_project.gen/sources_1/ip/data_fifo/data_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
